module.exports.auth = require("./auth")
module.exports.product = require("./product")
module.exports.review = require("./review")
module.exports.brand = require("./brand")
module.exports.purchase = require("./purchase")
module.exports.category = require("./category")
module.exports.subcategory = require("./subcategory")